# 站点名称
site_name: '123s'
# 仓库链接
repo_url: 
# 作者
site_author: 'big apple'
# 版权信息
copyright: 'big apple'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 1.0.0
# 主题
theme: 
    # name: 'readthedocs'
    name: 'mkdocs'

# markdown扩展
markdown_extensions:
    - toc:
        permalink: true


extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md

